//
//  MPrograssView.swift
//  Maths
//
//  Created by Maths on 7/18/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class MPrograssView : NSObject {

    //// Drawing Methods

    public class func drawCanvas1(#fraction: CGFloat, rectangle: CGRect, rectangle2: CGRect) {

        //// Variable Declarations
        let expression: CGFloat = 1 - 360 * fraction

        //// Oval Drawing
        var ovalRect = rectangle
        var ovalPath = UIBezierPath()
        ovalPath.addArcWithCenter(CGPointMake(ovalRect.midX, ovalRect.midY), radius: ovalRect.width / 2, startAngle: -(expression + 90) * CGFloat(M_PI)/180, endAngle: -90 * CGFloat(M_PI)/180, clockwise: false)
        ovalPath.addLineToPoint(CGPointMake(ovalRect.midX, ovalRect.midY))
        ovalPath.closePath()

        UIColor.redColor().setFill()
        ovalPath.fill()


        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: rectangle2)
        UIColor.clearColor().setFill()
        oval2Path.fill()
    }

    //// Generated Images

    public class func imageOfCanvas1(#fraction: CGFloat, rectangle: CGRect, rectangle2: CGRect) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(323, 236), false, 0)
            MPrograssView.drawCanvas1(fraction: fraction, rectangle: rectangle, rectangle2: rectangle2)

        let imageOfCanvas1 = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfCanvas1
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
